name: Startersteps Check

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check if Startersteps.md exists
        run: |
          if [[ -f "Startersteps.md" ]]; then
            echo "Make sure to complete all the steps in Startersteps.md, then delete the file"
            exit 1
          fi
